name: Volary Analyzer Agent
description: Analyses your repository for technical debt issues

inputs:
  completions-endpoint:
    description: 'URL for the completions API endpoint'
    required: false
  completions-api-key:
    description: 'API key for the completions endpoint'
    required: true
  coordinator-model:
    description: 'Model to use for coordinating the tech debt analysis'
    required: false
  delegate-model:
    description: 'Model to use for running delegated tasks'
    required: false

runs:
  using: docker
  image: Dockerfile
